// Auto-generated dataset file. Run preprocess_student_data.py to regenerate.
const DATA = [
  {
    "id": "STU001",
    "name": "Aarav Mehta",
    "sem": 3,
    "branch": "Computer Science",
    "cgpa": 8.2,
    "att": 85,
    "backlogs": 0,
    "asn": 90,
    "study": 5.0,
    "sleep": 7.0,
    "screen": 4.0,
    "exercise": 4,
    "friends": 8,
    "hostel": 1,
    "stress": 4,
    "pressure": 5,
    "motivation": 8,
    "club": 2,
    "intern": 1,
    "proj": 3,
    "cert": 2,
    "coding": 8,
    "burnout": 51,
    "placement": 100,
    "backlogRisk": 4,
    "loneliness": 16,
    "productivity": 93
  },
  {
    "id": "STU002",
    "name": "Priya Sharma",
    "sem": 5,
    "branch": "Computer Science",
    "cgpa": 6.1,
    "att": 62,
    "backlogs": 3,
    "asn": 55,
    "study": 2.0,
    "sleep": 5.0,
    "screen": 8.0,
    "exercise": 1,
    "friends": 2,
    "hostel": 1,
    "stress": 8,
    "pressure": 8,
    "motivation": 3,
    "club": 0,
    "intern": 0,
    "proj": 1,
    "cert": 0,
    "coding": 4,
    "burnout": 100,
    "placement": 64,
    "backlogRisk": 88,
    "loneliness": 84,
    "productivity": 27
  },
  {
    "id": "STU003",
    "name": "Rohan Patel",
    "sem": 7,
    "branch": "Mechanical",
    "cgpa": 7.5,
    "att": 78,
    "backlogs": 1,
    "asn": 75,
    "study": 4.0,
    "sleep": 6.5,
    "screen": 5.0,
    "exercise": 3,
    "friends": 5,
    "hostel": 1,
    "stress": 5,
    "pressure": 6,
    "motivation": 6,
    "club": 1,
    "intern": 2,
    "proj": 4,
    "cert": 3,
    "coding": 6,
    "burnout": 88,
    "placement": 100,
    "backlogRisk": 32,
    "loneliness": 44,
    "productivity": 71
  },
  {
    "id": "STU004",
    "name": "Sneha Gupta",
    "sem": 2,
    "branch": "Electronics",
    "cgpa": 9.1,
    "att": 95,
    "backlogs": 0,
    "asn": 98,
    "study": 7.0,
    "sleep": 8.0,
    "screen": 3.0,
    "exercise": 5,
    "friends": 10,
    "hostel": 0,
    "stress": 2,
    "pressure": 3,
    "motivation": 9,
    "club": 3,
    "intern": 0,
    "proj": 5,
    "cert": 4,
    "coding": 9,
    "burnout": 6,
    "placement": 100,
    "backlogRisk": 0,
    "loneliness": 0,
    "productivity": 100
  },
  {
    "id": "STU005",
    "name": "Karan Singh",
    "sem": 6,
    "branch": "Computer Science",
    "cgpa": 5.8,
    "att": 55,
    "backlogs": 5,
    "asn": 40,
    "study": 1.0,
    "sleep": 4.5,
    "screen": 10.0,
    "exercise": 0,
    "friends": 1,
    "hostel": 1,
    "stress": 9,
    "pressure": 9,
    "motivation": 2,
    "club": 0,
    "intern": 0,
    "proj": 0,
    "cert": 0,
    "coding": 3,
    "burnout": 100,
    "placement": 49,
    "backlogRisk": 100,
    "loneliness": 98,
    "productivity": 8
  },
  {
    "id": "STU006",
    "name": "Neha Joshi",
    "sem": 4,
    "branch": "Data Science",
    "cgpa": 7.9,
    "att": 80,
    "backlogs": 0,
    "asn": 82,
    "study": 5.0,
    "sleep": 7.0,
    "screen": 4.0,
    "exercise": 3,
    "friends": 6,
    "hostel": 0,
    "stress": 4,
    "pressure": 5,
    "motivation": 7,
    "club": 2,
    "intern": 1,
    "proj": 3,
    "cert": 3,
    "coding": 7,
    "burnout": 59,
    "placement": 100,
    "backlogRisk": 12,
    "loneliness": 26,
    "productivity": 85
  },
  {
    "id": "STU007",
    "name": "Vikram Rao",
    "sem": 8,
    "branch": "Computer Science",
    "cgpa": 8.7,
    "att": 88,
    "backlogs": 0,
    "asn": 92,
    "study": 6.0,
    "sleep": 7.5,
    "screen": 3.0,
    "exercise": 5,
    "friends": 7,
    "hostel": 1,
    "stress": 3,
    "pressure": 4,
    "motivation": 9,
    "club": 3,
    "intern": 2,
    "proj": 3,
    "cert": 5,
    "coding": 9,
    "burnout": 30,
    "placement": 100,
    "backlogRisk": 0,
    "loneliness": 12,
    "productivity": 100
  },
  {
    "id": "STU008",
    "name": "Anjali Verma",
    "sem": 1,
    "branch": "Civil",
    "cgpa": 6.5,
    "att": 70,
    "backlogs": 2,
    "asn": 60,
    "study": 3.0,
    "sleep": 6.0,
    "screen": 6.0,
    "exercise": 1,
    "friends": 3,
    "hostel": 1,
    "stress": 7,
    "pressure": 7,
    "motivation": 4,
    "club": 0,
    "intern": 0,
    "proj": 1,
    "cert": 0,
    "coding": 3,
    "burnout": 100,
    "placement": 70,
    "backlogRisk": 65,
    "loneliness": 71,
    "productivity": 44
  },
  {
    "id": "STU009",
    "name": "Arjun Kumar",
    "sem": 5,
    "branch": "Computer Science",
    "cgpa": 7.2,
    "att": 75,
    "backlogs": 1,
    "asn": 72,
    "study": 4.0,
    "sleep": 6.5,
    "screen": 5.0,
    "exercise": 2,
    "friends": 5,
    "hostel": 0,
    "stress": 5,
    "pressure": 6,
    "motivation": 6,
    "club": 1,
    "intern": 1,
    "proj": 3,
    "cert": 2,
    "coding": 6,
    "burnout": 89,
    "placement": 100,
    "backlogRisk": 36,
    "loneliness": 42,
    "productivity": 67
  },
  {
    "id": "STU010",
    "name": "Divya Nair",
    "sem": 3,
    "branch": "Data Science",
    "cgpa": 8.4,
    "att": 87,
    "backlogs": 0,
    "asn": 88,
    "study": 6.0,
    "sleep": 7.5,
    "screen": 3.0,
    "exercise": 4,
    "friends": 9,
    "hostel": 0,
    "stress": 3,
    "pressure": 4,
    "motivation": 8,
    "club": 2,
    "intern": 0,
    "proj": 4,
    "cert": 3,
    "coding": 8,
    "burnout": 31,
    "placement": 100,
    "backlogRisk": 0,
    "loneliness": 2,
    "productivity": 100
  },
  {
    "id": "STU011",
    "name": "Rahul Tiwari",
    "sem": 6,
    "branch": "Mechanical",
    "cgpa": 5.5,
    "att": 50,
    "backlogs": 6,
    "asn": 35,
    "study": 1.0,
    "sleep": 4.0,
    "screen": 11.0,
    "exercise": 0,
    "friends": 1,
    "hostel": 1,
    "stress": 9,
    "pressure": 8,
    "motivation": 2,
    "club": 0,
    "intern": 0,
    "proj": 0,
    "cert": 0,
    "coding": 2,
    "burnout": 100,
    "placement": 41,
    "backlogRisk": 100,
    "loneliness": 100,
    "productivity": 4
  },
  {
    "id": "STU012",
    "name": "Simran Kaur",
    "sem": 4,
    "branch": "Computer Science",
    "cgpa": 8.0,
    "att": 82,
    "backlogs": 0,
    "asn": 85,
    "study": 5.0,
    "sleep": 7.0,
    "screen": 4.0,
    "exercise": 3,
    "friends": 7,
    "hostel": 0,
    "stress": 4,
    "pressure": 5,
    "motivation": 7,
    "club": 2,
    "intern": 1,
    "proj": 1,
    "cert": 3,
    "coding": 7,
    "burnout": 57,
    "placement": 100,
    "backlogRisk": 10,
    "loneliness": 20,
    "productivity": 86
  },
  {
    "id": "STU013",
    "name": "Harsh Agarwal",
    "sem": 7,
    "branch": "Electronics",
    "cgpa": 6.8,
    "att": 68,
    "backlogs": 2,
    "asn": 65,
    "study": 3.0,
    "sleep": 5.5,
    "screen": 7.0,
    "exercise": 1,
    "friends": 2,
    "hostel": 1,
    "stress": 7,
    "pressure": 7,
    "motivation": 4,
    "club": 0,
    "intern": 1,
    "proj": 2,
    "cert": 1,
    "coding": 5,
    "burnout": 100,
    "placement": 90,
    "backlogRisk": 64,
    "loneliness": 80,
    "productivity": 42
  },
  {
    "id": "STU014",
    "name": "Pooja Reddy",
    "sem": 2,
    "branch": "Data Science",
    "cgpa": 9.3,
    "att": 96,
    "backlogs": 0,
    "asn": 99,
    "study": 8.0,
    "sleep": 8.0,
    "screen": 2.0,
    "exercise": 6,
    "friends": 11,
    "hostel": 0,
    "stress": 2,
    "pressure": 2,
    "motivation": 10,
    "club": 4,
    "intern": 0,
    "proj": 5,
    "cert": 5,
    "coding": 10,
    "burnout": 0,
    "placement": 100,
    "backlogRisk": 0,
    "loneliness": 0,
    "productivity": 100
  },
  {
    "id": "STU015",
    "name": "Amit Bhatt",
    "sem": 5,
    "branch": "Computer Science",
    "cgpa": 7.0,
    "att": 72,
    "backlogs": 1,
    "asn": 70,
    "study": 4.0,
    "sleep": 6.0,
    "screen": 5.0,
    "exercise": 2,
    "friends": 4,
    "hostel": 1,
    "stress": 6,
    "pressure": 6,
    "motivation": 5,
    "club": 1,
    "intern": 1,
    "proj": 1,
    "cert": 2,
    "coding": 6,
    "burnout": 100,
    "placement": 99,
    "backlogRisk": 44,
    "loneliness": 56,
    "productivity": 60
  },
  {
    "id": "STU016",
    "name": "Ishaan Desai",
    "sem": 3,
    "branch": "Mechanical",
    "cgpa": 6.3,
    "att": 64,
    "backlogs": 3,
    "asn": 55,
    "study": 2.0,
    "sleep": 5.0,
    "screen": 8.0,
    "exercise": 1,
    "friends": 2,
    "hostel": 1,
    "stress": 8,
    "pressure": 8,
    "motivation": 3,
    "club": 0,
    "intern": 0,
    "proj": 1,
    "cert": 0,
    "coding": 3,
    "burnout": 100,
    "placement": 63,
    "backlogRisk": 87,
    "loneliness": 84,
    "productivity": 28
  },
  {
    "id": "STU017",
    "name": "Meera Pillai",
    "sem": 8,
    "branch": "Electronics",
    "cgpa": 8.6,
    "att": 89,
    "backlogs": 0,
    "asn": 90,
    "study": 6.0,
    "sleep": 7.5,
    "screen": 3.0,
    "exercise": 5,
    "friends": 8,
    "hostel": 0,
    "stress": 3,
    "pressure": 3,
    "motivation": 9,
    "club": 3,
    "intern": 2,
    "proj": 2,
    "cert": 4,
    "coding": 8,
    "burnout": 21,
    "placement": 100,
    "backlogRisk": 0,
    "loneliness": 2,
    "productivity": 100
  },
  {
    "id": "STU018",
    "name": "Suresh Bhat",
    "sem": 6,
    "branch": "Civil",
    "cgpa": 5.2,
    "att": 48,
    "backlogs": 7,
    "asn": 30,
    "study": 1.0,
    "sleep": 3.5,
    "screen": 12.0,
    "exercise": 0,
    "friends": 0,
    "hostel": 1,
    "stress": 10,
    "pressure": 9,
    "motivation": 1,
    "club": 0,
    "intern": 0,
    "proj": 0,
    "cert": 0,
    "coding": 1,
    "burnout": 100,
    "placement": 32,
    "backlogRisk": 100,
    "loneliness": 100,
    "productivity": 0
  },
  {
    "id": "STU019",
    "name": "Kritika Soni",
    "sem": 4,
    "branch": "Data Science",
    "cgpa": 7.7,
    "att": 79,
    "backlogs": 0,
    "asn": 78,
    "study": 5.0,
    "sleep": 7.0,
    "screen": 4.0,
    "exercise": 3,
    "friends": 6,
    "hostel": 0,
    "stress": 4,
    "pressure": 5,
    "motivation": 7,
    "club": 2,
    "intern": 1,
    "proj": 0,
    "cert": 3,
    "coding": 7,
    "burnout": 60,
    "placement": 100,
    "backlogRisk": 14,
    "loneliness": 26,
    "productivity": 84
  },
  {
    "id": "STU020",
    "name": "Dev Malhotra",
    "sem": 1,
    "branch": "Computer Science",
    "cgpa": 7.4,
    "att": 74,
    "backlogs": 0,
    "asn": 73,
    "study": 4.0,
    "sleep": 6.5,
    "screen": 5.0,
    "exercise": 2,
    "friends": 1,
    "hostel": 0,
    "stress": 5,
    "pressure": 5,
    "motivation": 6,
    "club": 1,
    "intern": 0,
    "proj": 1,
    "cert": 1,
    "coding": 5,
    "burnout": 86,
    "placement": 92,
    "backlogRisk": 27,
    "loneliness": 66,
    "productivity": 68
  }
];
